name: Publish to npm

on:
  push:
    branches:
      - main  # 或者你希望触发发布的其他分支

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # 指定你使用的 Node.js 版本

      #- name: Install dependencies
      #  run: npm install

    #  - name: Build the package
     #   run: npm run build

      - name: Wait before publishing
        run: sleep 60  # 等待60秒
        
      - name: Publish to npm
        run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
